# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QStringListModel
from PyQt5.QtWidgets import QMessageBox, QInputDialog
from PyQt5.QtGui import QStandardItem, QStandardItemModel
import os
from SolveSQL import Solve
import pandas as pd
import re


class Ui_miniDBMS(QtWidgets.QMainWindow):
    def __init__(self, username):
        super(QtWidgets.QMainWindow, self).__init__()
        self.setupUi(self)
        self.username = username
        self.welcome = self.username + '，欢迎您使用本miniDBMS系统！'
        self.welcomedata = pd.DataFrame({'欢迎': [self.welcome]})
        self.setupData()
        self.pushButton.clicked.connect(self.loadtable)
        self.pushButton_2.clicked.connect(self.cleartable)
        self.pushButton_3.clicked.connect(self.textEdit.clear)
        self.pushButton_4.clicked.connect(self.SubmitSQL)

    def ProcessSQL(self, SQL):
        SQL = SQL.replace('\n', ' ')
        SQL = re.sub(' +', ' ', SQL)
        SQL = re.sub('; ', ';', SQL)
        SQList = SQL.split(';')
        for i in range(len(SQList)):
            words = SQList[i].split(' ')
            for j in range(len(words)):
                if 'NULL' not in words[j] and 'PRIMARY' not in words[j] and 'KEY' not in words[j] and 'NOT' not in words[j]:
                    words[j] = words[j].lower()
            SQList[i] = ' '.join(words)
        SQLlist = [x + ';' for x in SQList]
        SQLlist.pop()
        print(SQLlist)
        return SQLlist

    def SubmitSQL(self):
        SQL = self.textEdit.toPlainText()
        SQLlist = self.ProcessSQL(SQL)
        resultmessage, resulttype = [], []
        for SQL in SQLlist:
            result = Solve(SQL, self.username)
            if type(result[1]) == str:
                if result[0]:
                    resulttype.append('操作成功')
                else:
                    resulttype.append('操作失败')
                resultmessage.append(result[1])
            else:
                self.setDataFrame(result[1])
                return
        resultData = pd.DataFrame({'操作结果': resulttype, '提示':resultmessage})
        self.setDataFrame(resultData)
        self.setupData()

    def setupData(self):
        tablenames = os.listdir('./Data')
        tables = []
        for tablename in tablenames:
            if '.data' in tablename:
                tables.append(tablename.split('.')[0])
        tables.sort()
        tablelist = QStringListModel()
        tablelist.setStringList(tables)
        self.listView.setModel(tablelist)

    def setDataFrame(self, Data):
        self.model = QStandardItemModel(Data.shape[0], Data.shape[1])
        self.model.setHorizontalHeaderLabels(Data.columns.values)
        for row in range(Data.shape[0]):
            for column in range(Data.shape[1]):
                value = str(Data[Data.columns.values[column]][Data.index.values[row]])
                self.model.setItem(row, column, QStandardItem(value))
        self.tableView.setModel(self.model)
        self.tableView.resizeColumnsToContents()

    def loadtable(self):
        tablename = self.listView.selectionModel().selectedIndexes()[0].data()
        Data = pd.read_pickle('./Data/' + tablename + '.data')
        self.setDataFrame(Data)

    def cleartable(self):
        self.setDataFrame(self.welcomedata)

    def setupUi(self, miniDBMS):
        miniDBMS.setObjectName("miniDBMS")
        miniDBMS.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(miniDBMS)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 450, 221, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 500, 221, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(260, 50, 531, 191))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(430, 10, 171, 31))
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(260, 340, 531, 201))
        self.tableView.setObjectName("tableView")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(530, 250, 261, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(460, 300, 121, 31))
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(260, 250, 261, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(20, 20, 221, 411))
        self.listView.setObjectName("listView")
        miniDBMS.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(miniDBMS)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        miniDBMS.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(miniDBMS)
        self.statusbar.setObjectName("statusbar")
        miniDBMS.setStatusBar(self.statusbar)

        self.retranslateUi(miniDBMS)
        QtCore.QMetaObject.connectSlotsByName(miniDBMS)

    def retranslateUi(self, miniDBMS):
        _translate = QtCore.QCoreApplication.translate
        miniDBMS.setWindowTitle(_translate("miniDBMS", "miniDBMS系统"))
        self.pushButton.setText(_translate("miniDBMS", "加载表"))
        self.pushButton_2.setText(_translate("miniDBMS", "清空结果"))
        self.label.setText(_translate("miniDBMS", "SQL代码输入框"))
        self.pushButton_3.setText(_translate("miniDBMS", "清空"))
        self.label_2.setText(_translate("miniDBMS", "结果输出框"))
        self.pushButton_4.setText(_translate("miniDBMS", "提交"))